apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: mongodb
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: YWRtaW4= # admin (Base64)
  MONGO_INITDB_ROOT_PASSWORD: Um9oaXQ= # Rohit (Base64)
