apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: mysql
spec:
  storageClassName: standard # Check by -> kubectl get sc or kubectl get storageclass
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

